### ISSUE TITLE
ESP Home 2021.10.0 error

### ISSUE THREAD

**Issue by omerfaruk-aran** [berfenger/esphome_components#1]
Hello there;
Module fails after ESP Home 2021.10.0 update. :(

Error Detail:
`HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
PACKAGES: 
 - framework-arduinoespressif32 3.10006.210326 (1.0.6) 
 - tool-esptoolpy 1.30100.210531 (3.1.0) 
 - toolchain-xtensa32 2.50200.97 (5.2.0)
LDF Modes: Finder ~ off, Compatibility ~ soft
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 1.3.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
Compiling /data/aran-iot-11/.pioenvs/aran-iot-11/src/esphome/components/cse7761/cse7761.cpp.o
Compiling /data/aran-iot-11/.pioenvs/aran-iot-11/src/esphome/components/esp32/gpio_arduino.cpp.o
Compiling /data/aran-iot-11/.pioenvs/aran-iot-11/src/esphome/components/esp32/gpio_idf.cpp.o
Compiling /data/aran-iot-11/.pioenvs/aran-iot-11/src/esphome/components/esp32/preferences.cpp.o
In file included from src/esphome/components/sensor/sensor.h:3:0,
                 from src/esphome/components/cse7761/cse7761.h:3,
                 from src/esphome/components/cse7761/cse7761.cpp:1:
src/esphome/components/cse7761/cse7761.cpp: In member function 'bool esphome::cse7761::CSE7761Sensor::Cse7761ReadOnce(uint32_t, uint32_t, uint32_t*)':
src/esphome/components/cse7761/cse7761.cpp:221:38: error: 'PSTR' was not declared in this scope
     ESP_LOGD(TAG, PSTR("C61: Rx none"));
                                      ^
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^
src/esphome/core/log.h:155:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^
src/esphome/components/cse7761/cse7761.cpp:221:5: note: in expansion of macro 'ESP_LOGD'
     ESP_LOGD(TAG, PSTR("C61: Rx none"));
     ^
src/esphome/components/cse7761/cse7761.cpp:225:42: error: 'PSTR' was not declared in this scope
     ESP_LOGD(TAG, PSTR("C61: Rx overflow"));
                                          ^
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^
src/esphome/core/log.h:155:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^
src/esphome/components/cse7761/cse7761.cpp:225:5: note: in expansion of macro 'ESP_LOGD'
     ESP_LOGD(TAG, PSTR("C61: Rx overflow"));
     ^
src/esphome/components/cse7761/cse7761.cpp: In member function 'bool esphome::cse7761::CSE7761Sensor::Cse7761ChipInit()':
src/esphome/components/cse7761/cse7761.cpp:275:50: error: 'PSTR' was not declared in this scope
     ESP_LOGD(TAG, PSTR("C61: Default calibration"));
                                                  ^
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^
src/esphome/core/log.h:155:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^
src/esphome/components/cse7761/cse7761.cpp:275:5: note: in expansion of macro 'ESP_LOGD'
     ESP_LOGD(TAG, PSTR("C61: Default calibration"));
     ^
src/esphome/components/cse7761/cse7761.cpp:435:43: error: 'PSTR' was not declared in this scope
     ESP_LOGD(TAG, PSTR("C61: Write failed"));
                                           ^
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^
src/esphome/core/log.h:155:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^
src/esphome/components/cse7761/cse7761.cpp:435:5: note: in expansion of macro 'ESP_LOGD'
     ESP_LOGD(TAG, PSTR("C61: Write failed"));
     ^
src/esphome/components/cse7761/cse7761.cpp: In member function 'void esphome::cse7761::CSE7761Sensor::Cse7761GetData()':
src/esphome/components/cse7761/cse7761.cpp:471:53: error: 'PSTR' was not declared in this scope
   ESP_LOGD(TAG, PSTR("C61: F%d, U%d, I%d/%d, P%d/%d"), CSE7761Data.frequency,
                                                     ^
src/esphome/core/log.h:72:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
 #define ESPHOME_LOG_FORMAT(format) format
                                    ^
src/esphome/core/log.h:155:28: note: in expansion of macro 'esph_log_d'
 #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
                            ^
src/esphome/components/cse7761/cse7761.cpp:471:3: note: in expansion of macro 'ESP_LOGD'
   ESP_LOGD(TAG, PSTR("C61: F%d, U%d, I%d/%d, P%d/%d"), CSE7761Data.frequency,
   ^
*** [/data/aran-iot-11/.pioenvs/aran-iot-11/src/esphome/components/cse7761/cse7761.cpp.o] Error 1
========================= [FAILED] Took 10.08 seconds =========================`

**Comment by OmerAn2561** [comment]
> Hi,
> 
> the code mentioned on the trace does not correspond with the code on the latest version of the repo. Please, do a clean before compiling again. I just tried the component with the last version of esphome (2021.10.0) and it seems to work as it should.




I cleaned and tried again, but unfortunately the same problem persists.

**Comment by berfenger** [comment]
Try to delete the directory ".esphome" to force component download. This ".esphome" directory is located on the same location as your main yaml file.
