### ISSUE TITLE
MAX44009 sensor is not compatible with ESPHome 2021.10.x

### ISSUE THREAD

**Issue by anatoly-savchenkov** [berfenger/esphome_components#2]
Many I2CComponent methods were removed by this change https://github.com/esphome/esphome/pull/2303. This cases compilation issues like below.

BTW, Seems like your mcp4728 code has the same issue.

Processing esp32 (board: lolin_d32_pro; framework: arduino; platform: espressif32 @ 3.3.2)
--------------------------------------------------------------------------------
HARDWARE: ESP32 240MHz, 320KB RAM, 4MB Flash
Dependency Graph
|-- <AsyncTCP-esphome> 1.2.2
|-- <WiFi> 1.0
|-- <FS> 1.0
|-- <Update> 1.0
|-- <ESPAsyncWebServer-esphome> 2.0.0
|   |-- <AsyncTCP-esphome> 1.2.2
|-- <DNSServer> 1.1.0
|-- <SPI> 1.0
|-- <Wire> 1.0.1
|-- <ArduinoJson-esphomelib> 5.13.3
|-- <ESPmDNS> 1.0
....

Compiling /data/esp32/.pioenvs/esp32/src/esphome/components/max44009/max44009.cpp.o
src/esphome/components/max44009/max44009.cpp: In member function 'virtual void esphome::max44009::MAX44009Sensor::setup()':
src/esphome/components/max44009/max44009.cpp:32:9: error: 'class esphome::max44009::MAX44009Sensor' has no member named 'raw_begin_transmission'
   this->raw_begin_transmission();
         ^
src/esphome/components/max44009/max44009.cpp:33:14: error: 'class esphome::max44009::MAX44009Sensor' has no member named 'raw_end_transmission'
   if (!this->raw_end_transmission()) {
              ^
*** [/data/esp32/.pioenvs/esp32/src/esphome/components/max44009/max44009.cpp.o] Error 1

**Comment by berfenger** [comment]
Thank you for your report.
It is now fixed.

**Comment by anatoly-savchenkov** [comment]
Thank you for your efforts, it works well on my side. Looking forward to see this sensor in the main ESPHome source tree :)
